# Generated by Django 5.2 on 2025-05-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ingredient_recipeingredient_step_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['ingredient__name'], 'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
    ]
