# Generated by Django 5.2 on 2025-05-09 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_alter_ingredient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(verbose_name='Инструкция')),
                ('generation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Сохранен в кулинарную книгу')),
                ('base_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recipe', verbose_name='Базовый рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сгенерированный рецепт',
                'verbose_name_plural': 'Сгенерированные рецепты',
                'ordering': ['-generation_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50, verbose_name='Количество')),
                ('is_alternative', models.BooleanField(default=False, verbose_name='Альтернативный ингредиент')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_ingredients', to='recipe_generator.generatedrecipe')),
            ],
            options={
                'verbose_name': 'Ингредиент сгенерированного рецепта',
                'verbose_name_plural': 'Ингредиенты сгенерированных рецептов',
            },
        ),
        migrations.AddField(
            model_name='generatedrecipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe_generator.GeneratedRecipeIngredient', to='main.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.CreateModel(
            name='GeneratorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('any', 'Любая'), ('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='any', max_length=10, verbose_name='Уровень сложности')),
                ('max_cooking_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. время приготовления (мин)')),
                ('excluded_ingredients', models.ManyToManyField(blank=True, to='main.ingredient', verbose_name='Исключенные ингредиенты')),
                ('preferred_categories', models.ManyToManyField(blank=True, to='main.category', verbose_name='Предпочитаемые категории')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generator_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки генератора',
                'verbose_name_plural': 'Настройки генераторов',
            },
        ),
    ]
